language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  # gearman
  - sudo apt-get remove gearman-job-server
  - sudo apt-get install gearman-job-server libgearman-dev
  - printf "\n"| pecl install gearman-1.1.2
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - gearmand -d
  - phpunit

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm